### ISSUE TITLE
Issue with npm start

### ISSUE THREAD

**Issue by Davidhak1** [ryanmurakami/pizza-luvrs#28]
Hi Ryan, 
I'm getting the following error when run **npm start** on mac

TypeError: server.connection is not a function
    at Object.<anonymous> (/Users/path/pizza-luvrs-master/index.js:6:8)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pizza-luvrs@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pizza-luvrs@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dhakobyan/.npm/_logs/2019-06-26T22_18_01_075Z-debug.log

_Also, when I did npm install, I got these warnings, not sure if connected. But I ran **npm audit fix** and n**pm audit fix --force** it didn't help_ 

audited 318 packages in 0.769s
found 6 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

Also I cleaned npm cache, but it didn't help either.

**Comment by Davidhak1** [comment]
It's fixed I probably ran an audit fixed before, and it updated some libraries. So I deleted the repo and downloaded again ignoring all vulnerabilities. And **npm start** works fine now

Thanks!
