### ISSUE TITLE
npm start fails

### ISSUE THREAD

**Issue by faliure** [ryanmurakami/pizza-luvrs#31]
[ec2-user@ip-10-0-0-149 pizza-luvrs]$ **npm -v**
6.10.3
[ec2-user@ip-10-0-0-149 pizza-luvrs]$ **npm install**
added 155 packages from 236 contributors and audited 309 packages in 6.038s
found 57 vulnerabilities (4 low, 51 moderate, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
[ec2-user@ip-10-0-0-149 pizza-luvrs]$ **npm start**

> pizza-luvrs@1.0.0 start /home/ec2-user/pizza-luvrs
> node index.js

internal/modules/cjs/loader.js:775
    throw err;
    ^

Error: Cannot find module './data/mock.js'
Require stack:
- /home/ec2-user/pizza-luvrs/plugins.js
- /home/ec2-user/pizza-luvrs/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at /home/ec2-user/pizza-luvrs/plugins.js:72:5
    at /home/ec2-user/pizza-luvrs/node_modules/hapi/lib/plugin.js:323:16
    at done (/home/ec2-user/pizza-luvrs/node_modules/hapi/node_modules/items/lib/index.js:31:25)
    at Monitor.start (/home/ec2-user/pizza-luvrs/node_modules/good/lib/monitor.js:165:16)
    at Object.exports.register (/home/ec2-user/pizza-luvrs/node_modules/good/lib/index.js:42:20)
    at Object.target [as register] (/home/ec2-user/pizza-luvrs/node_modules/hapi/node_modules/joi/lib/object.js:79:30) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/ec2-user/pizza-luvrs/plugins.js',
    '/home/ec2-user/pizza-luvrs/index.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pizza-luvrs@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pizza-luvrs@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ec2-user/.npm/_logs/2019-09-07T03_17_13_929Z-debug.log
[ec2-user@ip-10-0-0-149 pizza-luvrs]$ **cat /home/ec2-user/.npm/_logs/2019-09-07T03_17_13_929Z-debug.log**
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/ec2-user/.nvm/versions/node/v12.10.0/bin/node',
1 verbose cli   '/home/ec2-user/.nvm/versions/node/v12.10.0/bin/npm',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.10.3
3 info using node@v12.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle pizza-luvrs@1.0.0~prestart: pizza-luvrs@1.0.0
6 info lifecycle pizza-luvrs@1.0.0~start: pizza-luvrs@1.0.0
7 verbose lifecycle pizza-luvrs@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle pizza-luvrs@1.0.0~start: PATH: /home/ec2-user/.nvm/versions/node/v12.10.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ec2-user/pizza-luvrs/node_modules/.bin:/home/ec2-user/.nvm/versions/node/v12.10.0/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/ec2-user/.local/bin:/home/ec2-user/bin
9 verbose lifecycle pizza-luvrs@1.0.0~start: CWD: /home/ec2-user/pizza-luvrs
10 silly lifecycle pizza-luvrs@1.0.0~start: Args: [ '-c', 'node index.js' ]
11 silly lifecycle pizza-luvrs@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle pizza-luvrs@1.0.0~start: Failed to exec start script
13 verbose stack Error: pizza-luvrs@1.0.0 start: `node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/ec2-user/.nvm/versions/node/v12.10.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:326:16)
13 verbose stack     at EventEmitter.emit (events.js:209:13)
13 verbose stack     at ChildProcess.<anonymous> (/home/ec2-user/.nvm/versions/node/v12.10.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:209:13)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid pizza-luvrs@1.0.0
15 verbose cwd /home/ec2-user/pizza-luvrs
16 verbose Linux 4.14.138-114.102.amzn2.x86_64
17 verbose argv "/home/ec2-user/.nvm/versions/node/v12.10.0/bin/node" "/home/ec2-user/.nvm/versions/node/v12.10.0/bin/npm" "start"
18 verbose node v12.10.0
19 verbose npm  v6.10.3
20 error code ELIFECYCLE
21 error errno 1
22 error pizza-luvrs@1.0.0 start: `node index.js`
22 error Exit status 1
23 error Failed at the pizza-luvrs@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by faliure** [comment]
Nvm, did a new clean scp and it worked, I'll remove this issue.
