### ISSUE TITLE
Make a pizza

### ISSUE THREAD

**Issue by pablotdv** [ryanmurakami/pizza-luvrs#44]
When I tried to make a pizza.
I have the error below.
```
Error [CredentialsError]: Missing credentials in config
    at IncomingMessage.<anonymous> (/home/ec2-user/pizza-luvrs/node_modules/aws-sdk/lib/util.js:888:34)
    at IncomingMessage.emit (events.js:322:22)
    at IncomingMessage.EventEmitter.emit (domain.js:482:12)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  message: 'Missing credentials in config',
  retryable: false,
  time: 2020-04-17T22:21:15.519Z,
  code: 'CredentialsError',
  originalError: {
    message: 'Could not load credentials from any providers',
    retryable: false,
    time: 2020-04-17T22:21:15.518Z,
    code: 'CredentialsError'
  }
} null
```

**Comment by ryanmurakami** [comment]
Hi Pablo, looks like you need to setup your aws cli. Run ‘aws configure’ in your command line and add your credentials that way.

**Comment by pablotdv** [comment]
Another way is put the KeyId and AccesKey in `imageStoreS3.js`

```
const AWS = require('aws-sdk')
AWS.config = AWS.config
AWS.config.accessKeyId = "######";
AWS.config.secretAccessKey = "######";
```
