### ISSUE TITLE
Getting startup error when running npm start

### ISSUE THREAD

**Issue by sum1991** [ryanmurakami/pizza-luvrs#71]
Hi   @ryanmurakami following your tutorial for aws dev cert.. but running into this error.. when runing npm start.
node version v10.16.0

❯ node index.js
/Users/lagadas/Documents/awsTutorial/pizza-luvrs/index.js:25
  console.error(`Reason: ${reason.message}, Stack: ${reason?.stack}`)
                                                            ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

**Comment by ryanmurakami** [comment]
Hi @sum1991, Thanks for creating the issue! This is an error with earlier versions of Node.js. Can you update to version 14+ and try again? Thanks!

**Comment by adarkkiss** [comment]
Hello I am also having this issue with the latest update and it keeps giving me errors that it can't be found when everything is in the same file

**Comment by dextel2** [comment]
@sum1991 and @adarkkiss I have cloned the repo and run the code and it works perfectly fine with node v16.14.0.
